export const MicroNutrimentsConst = {
  VITAMINE_A: { label: 'Vitamine A', value: 800, unit: 'μg' },
  VITAMINE_B1: { label: 'Vitamine B1', value: 1.1, unit: 'mg' },
  VITAMINE_B2: { label: 'Vitamine B2', value: 1.4, unit: 'mg' },
  VITAMINE_B3: { label: 'Vitamine B3', value: 16, unit: 'mg' },
  VITAMINE_B5: { label: 'Vitamine B5', value: 6, unit: 'mg' },
  VITAMINE_B6: { label: 'Vitamine B6', value: 1.4, unit: 'mg' },
  VITAMINE_B8: { label: 'Vitamine B8', value: 50, unit: 'μg' },
  VITAMINE_B9: { label: 'Vitamine A', value: 200, unit: 'μg' },
  VITAMINE_B12: { label: 'Vitamine B12', value: 2.5, unit: 'μg' },
  VITAMINE_C: { label: 'Vitamine C', value: 80, unit: 'mg' },
  VITAMINE_D: { label: 'Vitamine D', value: 5, unit: 'μg' },
  VITAMINE_E: { label: 'Vitamine E', value: 12, unit: 'mg' },
  VITAMINE_K: { label: 'Vitamine K', value: 75, unit: 'μg' },
  CALCIUM: { label: 'Calcium', value: 800, unit: 'mg' },
  FER: { label: 'Fer', value: 14, unit: 'mg' },
  IODE: { label: 'Iode', value: 150, unit: 'μg' },
  MAGNESIUM: { label: 'Magnésium', value: 375, unit: 'mg' },
  PHOSPHORE: { label: 'Phosphore', value: 700, unit: 'mg' },
  SELENIUM: { label: 'Sélenium', value: 55, unit: 'μg' },
  ZINC: { label: 'Zinc', value: 10, unit: 'mg' },
  POTASSIUM: { label: 'Potassium', value: 2000, unit: 'mg' },
  CHLORURE: { label: 'Chlore', value: 800, unit: 'mg' },
  COPPER: { label: 'Cuivre', value: 1, unit: 'mg' },
  MANGANESE: { label: 'Manganèse', value: 3, unit: 'mg' },
  FLUORURE: { label: 'Fluor', value: 3.5, unit: 'mg' },
  CHROME: { label: 'Chrome', value: 40, unit: 'μg' },
  MOLYBDENE: { label: 'Molybdène', value: 50, unit: 'μg' },
  SODIUM: { label: 'Sodium', value: 800, unit: 'mg' },
  CHOLESTEROL: { label: 'Cholesterol', value: 300, unit: 'mg' },
};

export const NutrimentsManConst = {
  ENERGY_KJ: { label: 'Joules', value: 2500 * 4.13, unit: 'kJ' },
  CALORIES: { label: 'Calories', value: 2500, unit: 'kcal' },
  LIPIDES: { label: 'Lipides', value: 84, unit: 'g' },
  SATURATED_FAT: { label: 'Acides gras saturés', value: 26, unit: 'g' },
  GLUCIDES: { label: 'Glucides', value: 312, unit: 'g' },
  SUGARS: { label: 'Sucres', value: 25, unit: 'g' },
  PROTEINES: { label: 'Protéines', value: 124, unit: 'g' },
  FIBERS: { label: 'Fibres', value: 30, unit: 'g' },
  SALT: { label: 'Sel', value: 5, unit: 'g' },
};

export const NutrimentsWomanConst = {
  ENERGY_KJ: {
    label: NutrimentsManConst.ENERGY_KJ.label,
    value: NutrimentsManConst.ENERGY_KJ.value * 0.8,
    unit: NutrimentsManConst.ENERGY_KJ.unit,
  },
  CALORIES: {
    label: NutrimentsManConst.CALORIES.label,
    value: NutrimentsManConst.CALORIES.value * 0.8,
    unit: NutrimentsManConst.CALORIES.unit,
  },
  LIPIDES: {
    label: NutrimentsManConst.LIPIDES.label,
    value: NutrimentsManConst.LIPIDES.value * 0.8,
    unit: NutrimentsManConst.LIPIDES.unit,
  },
  SATURATED_FAT: {
    label: NutrimentsManConst.SATURATED_FAT.label,
    value: NutrimentsManConst.SATURATED_FAT.value * 0.8,
    unit: NutrimentsManConst.SATURATED_FAT.unit,
  },
  GLUCIDES: {
    label: NutrimentsManConst.GLUCIDES.label,
    value: NutrimentsManConst.GLUCIDES.value * 0.8,
    unit: NutrimentsManConst.GLUCIDES.unit,
  },
  SUGARS: {
    label: NutrimentsManConst.SUGARS.label,
    value: NutrimentsManConst.SUGARS.value * 0.8,
    unit: NutrimentsManConst.SUGARS.unit,
  },
  PROTEINES: {
    label: NutrimentsManConst.PROTEINES.label,
    value: NutrimentsManConst.PROTEINES.value * 0.8,
    unit: NutrimentsManConst.PROTEINES.unit,
  },
  FIBERS: {
    label: NutrimentsManConst.FIBERS.label,
    value: NutrimentsManConst.FIBERS.value * 0.8,
    unit: NutrimentsManConst.FIBERS.unit,
  },
  SALT: {
    label: NutrimentsManConst.SALT.label,
    value: NutrimentsManConst.SALT.value * 0.8,
    unit: NutrimentsManConst.SALT.unit,
  },
};
